name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        run: ./gradlew build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bread-and-shampoo
          path: |
            build/libs/*
